on: push
name: PHP CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_DATABASE: postgres        
          POSTGRES_PASSWORD: 1111
          POSTGRES_USER: postgres
          POSTGRES_HOST: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup project
      run: make setup

    - name: Run linter
      run: make lint

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID_4}}
      with:
        coverageCommand: make test-coverage
        debug: true

    - name: Run Tests
      run: make test
