on: push
name: PHP CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_DATABASE: postgres        
          POSTGRES_PASSWORD: 1111
          POSTGRES_USER: postgres
          POSTGRES_HOST: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup project
      run: make setup

    - name: Run linter
      run: make lint

    - name: Run code-climate test-coverage
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 0a9508657c3197a14a9cb44767247d0da5b86da88b720e4b596eb5a471bb05c0

    - name: Run Tests
      run: make test
